name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-example:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: pull docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/python-example:latest

      - name: stop old container if running
        run: |
          if [ "$(docker ps -q -f ancestor=${{ secrets.DOCKERHUB_USERNAME }}/python-example)" ]; then
              docker stop $(docker ps -q -f ancestor=${{ secrets.DOCKERHUB_USERNAME }}/python-example)
              docker rm $(docker ps -a -q -f ancestor=${{ secrets.DOCKERHUB_USERNAME }}/python-example)
          fi

      - name: run new container
        run: |
          docker run -d -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/python-example:latest
